### ISSUE TITLE
Powershell DNS client is sending malformed data

### ISSUE THREAD

**Issue by ChrisTruncer** [FortyNorthSecurity/Egress-Assess#39]
DNS client is sending malformed data when using the powershell client of Egress-Assess.

**Comment by ChrisTruncer** [comment]
Looks like we may have to remove DNS from powershell - you agree @rvrsh3ll ?

**Comment by c0d3xpl0it** [comment]
Dear Chris,

The powershell client doesn't support DNS ? 

![image](https://user-images.githubusercontent.com/8144002/31938973-050f8c8e-b8ca-11e7-8c29-46c728dd790e.png)

**Comment by ChrisTruncer** [comment]
Nope, not at the moment

**Comment by khr0x40sh** [comment]
I've done some work on a forked version of this and have some "fixes" to DNS in the powershell code.  Who should I discuss sending a PR to?

**Comment by ChrisTruncer** [comment]
I'm happy to look at it, if available, @rvrsh3ll might be able to as well, but I'm certainly happy to check it out. Feel free to open a pull request and we can discuss everything in it.

**Comment by rvrsh3ll** [comment]
Yeah, If you want to submit a PR one of us will check it out.

**Comment by butlerallenj** [comment]
I think this one can be closed by #54 fellas

**Comment by ChrisTruncer** [comment]
yup, closing
