### ISSUE TITLE
Specify port for powershell client

### ISSUE THREAD

**Issue by Raikia** [FortyNorthSecurity/Egress-Assess#52]
It'd be nice if you could specify the port to send data on in the Powershell version.  You can set the server port number for the listener server-side, but not the client-side.  For example, I can't test FTP data over port 1234 because the powershell client doesnt accept an alternate port.

**Comment by ChrisTruncer** [comment]
Yeah, that's a good idea and I've been asked this before too. I'll look to get this added in.

**Comment by ChrisTruncer** [comment]
Just merged this is for nearly all protocols (except ICMP, SMB, and DNS since server side those use scapy to parse incoming packets)

**Comment by Raikia** [comment]
Now thats service! Thanks!
