### ISSUE TITLE
Generate-CreditCards writing files to disk

### ISSUE THREAD

**Issue by Raikia** [FortyNorthSecurity/Egress-Assess#55]
I'm pretty confident this was a debugging statement for you at some point that made it into master:

https://github.com/FortyNorthSecurity/Egress-Assess/blob/master/EgressAssess.ps1#L357

Generate-CreditCards drops a file named CCData.txt

![image](https://i.imgur.com/XZTAjay.png)

**Comment by ChrisTruncer** [comment]
Yeah...

You're right... :)

I'll get that removed, thanks for the heads up!

**Comment by ChrisTruncer** [comment]
Merged in the removal of that. Thanks for the heads up @Raikia
