### ISSUE TITLE
Transfer error when using the .ps1 using FTP/DNS client session.

### ISSUE THREAD

**Issue by harleyQu1nn** [FortyNorthSecurity/Egress-Assess#58]
VERBOSE: [*] Testing server connection
VERBOSE: [*] Server is UP on <Redacted IP>.
VERBOSE: [*] FTP Server Running on <Redacted IP> port 21.
VERBOSE: [*] Generating 50 MB of Credit Cards (1500000)...

[+] received output:
VERBOSE: [*] Uploading data..

[+] received output:
VERBOSE: [*] Error, tranfer failed with error:
VERBOSE: Exception calling "UploadString" with "2" argument(s): "The remote server returned an error: 227 Entering passive mode (<redacted>,234,183).
."
VERBOSE: [*] Exiting..

Tried with ufw fw rules in place and also opening up the server to allow any connection to and from FTP. Still the same error comes up.

**Comment by harleyQu1nn** [comment]
Turned out to be a block in place client side. Disregard.

**Comment by ChrisTruncer** [comment]
Ah nice. Well thank you for reporting this originally, and then giving an update, I appreciate it!

**Comment by harleyQu1nn** [comment]
Turns out it wasn't actually blocked by the client systems. FTP won't work with Ubuntu 18.04 systems as I get the same error:

VERBOSE: [] Testing server connection
VERBOSE: [] Server is UP on .
VERBOSE: [] FTP Server Running on port 21.
VERBOSE: [] Generating 50 MB of Credit Cards (1500000)...

[+] received output:
VERBOSE: [*] Uploading data..

[+] received output:
VERBOSE: [] Error, tranfer failed with error:
VERBOSE: Exception calling "UploadString" with "2" argument(s): "The remote server returned an error: 227 Entering passive mode (,234,183).
."
VERBOSE: [] Exiting..

NOTE: It did work on Ubuntu 16.04 and below systems. 

Also DNS won't transfer either. Receiving the error for DNS on Ubuntu 18.04 systems: 
[*] Error, DNS data tranfer failed with error:
VERBOSE: Exception calling "Substring" with "2" argument(s): "Index and length must refer to a location within the string.
Parameter name: length"
VERBOSE: [*] Transfer complete!
VERBOSE: [*] 0 loops remaining..
VERBOSE: [*] Exiting..

Something to note about Ubuntu 18.04 systems: DNS port 53 is already in use by the systemd-resolved service which will deny you from using Egress-Assess for DNS as the port is already in use.

Not sure of a good work around here other than using older versions of Ubuntu or Debian based.

**Comment by ChrisTruncer** [comment]
Ah, thanks for further looking into this. At this point, I would say you are likely right. I don't want to make operating system configuration changes for the tool. I would prefer the user knowingly make those changes, vs. the tool making the change and the user not knowing it happened.

Personally, I'll use debian when testing and if the issue is because DNS is by default running on Ubuntu 18.04+ and causing this issue, I'll update the README to state the fact.

Since I don't want to make any changes to an OS, I'm going to close this issue once I update the README. Thanks again

**Comment by ChrisTruncer** [comment]
Just merged in this update, so I will close this out.
